package com.hsenid.reader;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.security.NoSuchAlgorithmException;
import java.util.*;
import java.util.Timer;


/**
 * Created by hsenid on 1/17/17.
 */
public class LoginForm extends JFrame {
    private JTextField TxtUserName;
    private JPasswordField TxtPassword;
    private JButton logInButton;
    private JPanel LogInForm;
    private String txtUserName;
    private String txtPassword;
    private UserJDBCTemplate userJdbcTemplate;
    private Utilities utilities;
    private ParentWindow pWindow;

    public void setpWindow(ParentWindow pWindow) {
        this.pWindow = pWindow;
    }

    public LoginForm() {
        add(LogInForm);
        FormLoading();
        logInButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e
             */
            public void actionPerformed(ActionEvent e) {
                String UserName = TxtUserName.getText();
                String Password = null;
                try {
                    Password = utilities.getSHA(new String(TxtPassword.getPassword()), 1);
                } catch (NoSuchAlgorithmException e1) {
                    e1.printStackTrace();
                }

                User currentUser = userJdbcTemplate.getUser(UserName);
                if (currentUser == null || !currentUser.getUsr_pass().equals(Password)) {
                    JOptionPane failDialogPane = new JOptionPane("Login Fail", JOptionPane.ERROR_MESSAGE);
                    final JDialog failDialog = failDialogPane.createDialog(null, "Error!");
                    Timer timer = new Timer();
                    timer.schedule(new TimerTask() {
                        @Override
                        public void run() {
                            failDialog.setVisible(false);
                        }
                    }, 5000);
                    failDialog.setVisible(true);

                } else {
                    terminateLogin();
                    pWindow.loadParentWindow();
                }

            }
        });
    }


    private void FormLoading() {
        setTitle("LogIn Form");
        setResizable(false);
        setSize(300, 150);
        setContentPane(LogInForm);
        addStyle();
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
    }

    public void addStyle() {
        try {

            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                } else {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                }
            }

        } catch (Exception e) {

            e.printStackTrace();
        }
    }

    public void terminateLogin() {
        setVisible(false);
        dispose();
    }

    public void setTxtUserName(String TxtUserName) {
        txtUserName = TxtUserName;
    }

    public String getTxtUserName() {
        return txtUserName;
    }

    public void setTxtPassword(String TxtPassword) {
        txtPassword = TxtPassword;
    }

    public String getTxtPassword() {
        return txtPassword;
    }

    public UserJDBCTemplate getUserJdbcTemplate() {
        return userJdbcTemplate;
    }

    public void setUserJdbcTemplate(UserJDBCTemplate userJdbcTemplate) {
        this.userJdbcTemplate = userJdbcTemplate;
    }

    public Utilities getUtilities() {
        return utilities;
    }

    public void setUtilities(Utilities utilities) {
        this.utilities = utilities;
    }

    public static void main(String[] args) {
        LoginForm obj = new LoginForm();

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LogInForm = new JPanel();
        LogInForm.setLayout(new GridBagLayout());
        LogInForm.setBackground(new Color(-65794));
        final JLabel label1 = new JLabel();
        label1.setText("User Name");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(10, 5, 0, 5);
        LogInForm.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Password");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(0, 5, 0, 5);
        LogInForm.add(label2, gbc);
        TxtUserName = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 10.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 15, 0, 15);
        LogInForm.add(TxtUserName, gbc);
        TxtPassword = new JPasswordField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 10.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 15, 0, 15);
        LogInForm.add(TxtPassword, gbc);
        logInButton = new JButton();
        logInButton.setBackground(new Color(-1711135));
        logInButton.setText("LogIn");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 50, 0, 50);
        LogInForm.add(logInButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LogInForm;
    }
}
