package com.hsenid.reader;

import javax.swing.*;
import java.awt.*;
import java.util.Iterator;

/**
 * Created by Vidushka on 18/01/17.
 */
public class ViewBookDetails extends JInternalFrame {
    private JPanel panelX;
    JTextField txtTitle;
    JTextField txtKeyWord;
    JLabel lblKeyWord;
    JLabel lblTitle;
    JTextArea bookList;
    JButton btnSearch;
    private JList<Book> bookViewList;
    //private BookJDBCTemplate bookJDBCTemplate;
    int i = 0;


    public ViewBookDetails(BookJDBCTemplate bookJDBCTemplate) {
        super("Books", true, true, true, true);
        DefaultListModel<Book> books = new DefaultListModel<>();

        while (i < bookJDBCTemplate.getBookList().size()) {
            books.add(i, bookJDBCTemplate.getBookList().get(i));
            i++;
        }

        bookViewList.setModel(books);
        add(panelX);
        pack();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelX = new JPanel();
        panelX.setLayout(new GridBagLayout());
        panelX.setBackground(new Color(-9702673));
        lblTitle = new JLabel();
        lblTitle.setText("Find Title");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(lblTitle, gbc);
        lblKeyWord = new JLabel();
        lblKeyWord.setText("Find KeyWords");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(lblKeyWord, gbc);
        bookList = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weighty = 20.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(bookList, gbc);
        txtTitle = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 20.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(txtTitle, gbc);
        txtKeyWord = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 20.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(txtKeyWord, gbc);
        btnSearch = new JButton();
        btnSearch.setText("Search");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panelX.add(btnSearch, gbc);
        bookViewList = new JList();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.weighty = 10.0;
        gbc.fill = GridBagConstraints.BOTH;
        panelX.add(bookViewList, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelX;
    }

    /*public BookJDBCTemplate getBookJDBCTemplate() {
        return bookJDBCTemplate;
    }

    public void setBookJDBCTemplate(BookJDBCTemplate bookJDBCTemplate) {
        this.bookJDBCTemplate = bookJDBCTemplate;
    }*/

}