package com.hsenid.reader;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.DefaultEditorKit;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
import java.util.List;

/**
 * Created by Vidushka on 18/01/17.
 */
public class ViewBookDetails extends JInternalFrame {
    private JPanel panelX;
    JTextField txtTitle;
    JTextField txtKeyWord;
    JLabel lblKeyWord;
    JLabel lblTitle;
    JButton btnSearch;
    private JList<String> bookViewList;
    int i = 0;

    public ViewBookDetails(BookJDBCTemplate bookJDBCTemplate) {
        super("Books", true, true, true, true);
        DefaultListModel<String> books = new DefaultListModel<>();

        List<Book> bkList = bookJDBCTemplate.getBookList();
        while (i < bkList.size()) {
            books.add(i, (bkList.get(i).getBk_title() + " | " + bkList.get(i).getBk_author() + " | " +
                    bkList.get(i).getBk_desc()));
            i++;
        }

        bookViewList.setModel(books);
        add(panelX);
        pack();

        bookViewList.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                if (SwingUtilities.isRightMouseButton(me)) {
                    String[] buttons = {"Download", "Update", "Delete"};
                    int selectedOption = JOptionPane.showOptionDialog(null, "", "Select a option",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, buttons, buttons[0]);

                    if (selectedOption == 0) {
                        System.out.println("Method for download " + bookViewList.getSelectedValue());
                    } else if (selectedOption == 1) {
                        System.out.println("Method for update " + bookViewList.getSelectedValue());
                    } else if (selectedOption == 2) {
                        System.out.println("Method for delete " + bookViewList.getSelectedValue());
                    }
                }
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelX = new JPanel();
        panelX.setLayout(new GridBagLayout());
        panelX.setBackground(new Color(-9702673));
        lblTitle = new JLabel();
        lblTitle.setText("Find Title");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(lblTitle, gbc);
        lblKeyWord = new JLabel();
        lblKeyWord.setText("Find KeyWords");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(lblKeyWord, gbc);
        txtTitle = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 20.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(txtTitle, gbc);
        txtKeyWord = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 20.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(txtKeyWord, gbc);
        btnSearch = new JButton();
        btnSearch.setText("Search");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panelX.add(btnSearch, gbc);
        bookViewList = new JList();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.weighty = 20.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(5, 5, 5, 5);
        panelX.add(bookViewList, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelX;
    }

    /*public void mouseClicked(MouseEvent e)
    {
        if (e.getClickCount() == 2)
        {
            Action action = list.getActionMap().get(keyStroke);

            if (action != null)
            {
                ActionEvent event = new ActionEvent(
                        list,
                        ActionEvent.ACTION_PERFORMED,
                        "");
                action.actionPerformed(event);
            }
        }
    }*/

    /*public BookJDBCTemplate getBookJDBCTemplate() {
        return bookJDBCTemplate;
    }

    public void setBookJDBCTemplate(BookJDBCTemplate bookJDBCTemplate) {
        this.bookJDBCTemplate = bookJDBCTemplate;
    }*/

}